//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestProject20200713
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact type.
    /// </summary>
    //  *** Start programmer edit section *** (ContactType CustomAttributes)

    //  *** End programmer edit section *** (ContactType CustomAttributes)
    [AutoAltered()]
    [Caption("Contact type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContactTypeE", new string[] {
            "TypeName as \'Type name\'"})]
    [View("ContactTypeL", new string[] {
            "TypeName as \'Type name\'"})]
    public class ContactType : ICSSoft.STORMNET.DataObject
    {
        
        private string fTypeName;
        
        //  *** Start programmer edit section *** (ContactType CustomMembers)

        //  *** End programmer edit section *** (ContactType CustomMembers)

        
        /// <summary>
        /// TypeName.
        /// </summary>
        //  *** Start programmer edit section *** (ContactType.TypeName CustomAttributes)

        //  *** End programmer edit section *** (ContactType.TypeName CustomAttributes)
        [StrLen(255)]
        public virtual string TypeName
        {
            get
            {
                //  *** Start programmer edit section *** (ContactType.TypeName Get start)

                //  *** End programmer edit section *** (ContactType.TypeName Get start)
                string result = this.fTypeName;
                //  *** Start programmer edit section *** (ContactType.TypeName Get end)

                //  *** End programmer edit section *** (ContactType.TypeName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ContactType.TypeName Set start)

                //  *** End programmer edit section *** (ContactType.TypeName Set start)
                this.fTypeName = value;
                //  *** Start programmer edit section *** (ContactType.TypeName Set end)

                //  *** End programmer edit section *** (ContactType.TypeName Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContactTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactTypeE", typeof(IIS.TestProject20200713.ContactType));
                }
            }
            
            /// <summary>
            /// "ContactTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactTypeL", typeof(IIS.TestProject20200713.ContactType));
                }
            }
        }
    }
}
