//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestProject20200713
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact.
    /// </summary>
    //  *** Start programmer edit section *** (Contact CustomAttributes)

    //  *** End programmer edit section *** (Contact CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContactE", new string[] {
            "FirName as \'Fir name\'",
            "SurName as \'Sur name\'",
            "SecName as \'Sec name\'",
            "ContactType as \'Contact type\'",
            "ContactType.TypeName as \'Type name\'"})]
    [AssociatedDetailViewAttribute("ContactE", "Phone", "PhoneE", true, "", "Phone", true, new string[] {
            ""})]
    [View("ContactL", new string[] {
            "FirName as \'Fir name\'",
            "SurName as \'Sur name\'",
            "SecName as \'Sec name\'",
            "ContactType.TypeName as \'Type name\'"})]
    public class Contact : ICSSoft.STORMNET.DataObject
    {
        
        private string fFirName;
        
        private string fSurName;
        
        private string fSecName;
        
        private IIS.TestProject20200713.ContactType fContactType;
        
        private IIS.TestProject20200713.DetailArrayOfPhone fPhone;
        
        //  *** Start programmer edit section *** (Contact CustomMembers)

        //  *** End programmer edit section *** (Contact CustomMembers)

        
        /// <summary>
        /// FirName.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.FirName CustomAttributes)

        //  *** End programmer edit section *** (Contact.FirName CustomAttributes)
        [StrLen(255)]
        public virtual string FirName
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.FirName Get start)

                //  *** End programmer edit section *** (Contact.FirName Get start)
                string result = this.fFirName;
                //  *** Start programmer edit section *** (Contact.FirName Get end)

                //  *** End programmer edit section *** (Contact.FirName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.FirName Set start)

                //  *** End programmer edit section *** (Contact.FirName Set start)
                this.fFirName = value;
                //  *** Start programmer edit section *** (Contact.FirName Set end)

                //  *** End programmer edit section *** (Contact.FirName Set end)
            }
        }
        
        /// <summary>
        /// SurName.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.SurName CustomAttributes)

        //  *** End programmer edit section *** (Contact.SurName CustomAttributes)
        [StrLen(255)]
        public virtual string SurName
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.SurName Get start)

                //  *** End programmer edit section *** (Contact.SurName Get start)
                string result = this.fSurName;
                //  *** Start programmer edit section *** (Contact.SurName Get end)

                //  *** End programmer edit section *** (Contact.SurName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.SurName Set start)

                //  *** End programmer edit section *** (Contact.SurName Set start)
                this.fSurName = value;
                //  *** Start programmer edit section *** (Contact.SurName Set end)

                //  *** End programmer edit section *** (Contact.SurName Set end)
            }
        }
        
        /// <summary>
        /// SecName.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.SecName CustomAttributes)

        //  *** End programmer edit section *** (Contact.SecName CustomAttributes)
        [StrLen(255)]
        public virtual string SecName
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.SecName Get start)

                //  *** End programmer edit section *** (Contact.SecName Get start)
                string result = this.fSecName;
                //  *** Start programmer edit section *** (Contact.SecName Get end)

                //  *** End programmer edit section *** (Contact.SecName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.SecName Set start)

                //  *** End programmer edit section *** (Contact.SecName Set start)
                this.fSecName = value;
                //  *** Start programmer edit section *** (Contact.SecName Set end)

                //  *** End programmer edit section *** (Contact.SecName Set end)
            }
        }
        
        /// <summary>
        /// Contact.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.ContactType CustomAttributes)

        //  *** End programmer edit section *** (Contact.ContactType CustomAttributes)
        [NotNull()]
        public virtual IIS.TestProject20200713.ContactType ContactType
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.ContactType Get start)

                //  *** End programmer edit section *** (Contact.ContactType Get start)
                IIS.TestProject20200713.ContactType result = this.fContactType;
                //  *** Start programmer edit section *** (Contact.ContactType Get end)

                //  *** End programmer edit section *** (Contact.ContactType Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.ContactType Set start)

                //  *** End programmer edit section *** (Contact.ContactType Set start)
                this.fContactType = value;
                //  *** Start programmer edit section *** (Contact.ContactType Set end)

                //  *** End programmer edit section *** (Contact.ContactType Set end)
            }
        }
        
        /// <summary>
        /// Contact.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.Phone CustomAttributes)

        //  *** End programmer edit section *** (Contact.Phone CustomAttributes)
        public virtual IIS.TestProject20200713.DetailArrayOfPhone Phone
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.Phone Get start)

                //  *** End programmer edit section *** (Contact.Phone Get start)
                if ((this.fPhone == null))
                {
                    this.fPhone = new IIS.TestProject20200713.DetailArrayOfPhone(this);
                }
                IIS.TestProject20200713.DetailArrayOfPhone result = this.fPhone;
                //  *** Start programmer edit section *** (Contact.Phone Get end)

                //  *** End programmer edit section *** (Contact.Phone Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.Phone Set start)

                //  *** End programmer edit section *** (Contact.Phone Set start)
                this.fPhone = value;
                //  *** Start programmer edit section *** (Contact.Phone Set end)

                //  *** End programmer edit section *** (Contact.Phone Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContactE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactE", typeof(IIS.TestProject20200713.Contact));
                }
            }
            
            /// <summary>
            /// "ContactL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactL", typeof(IIS.TestProject20200713.Contact));
                }
            }
        }
    }
}
