//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestProject20200713
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Phone.
    /// </summary>
    //  *** Start programmer edit section *** (Phone CustomAttributes)

    //  *** End programmer edit section *** (Phone CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PhoneE", new string[] {
            "Number as \'Number\'",
            "PhoneType as \'Phone type\'",
            "PhoneType.TypeName as \'Type name\'"}, Hidden=new string[] {
            "PhoneType.TypeName"})]
    [MasterViewDefineAttribute("PhoneE", "PhoneType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "TypeName")]
    public class Phone : ICSSoft.STORMNET.DataObject
    {
        
        private string fNumber;
        
        private IIS.TestProject20200713.PhoneType fPhoneType;
        
        private IIS.TestProject20200713.Contact fContact;
        
        //  *** Start programmer edit section *** (Phone CustomMembers)

        //  *** End programmer edit section *** (Phone CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        //  *** Start programmer edit section *** (Phone.Number CustomAttributes)

        //  *** End programmer edit section *** (Phone.Number CustomAttributes)
        [StrLen(255)]
        public virtual string Number
        {
            get
            {
                //  *** Start programmer edit section *** (Phone.Number Get start)

                //  *** End programmer edit section *** (Phone.Number Get start)
                string result = this.fNumber;
                //  *** Start programmer edit section *** (Phone.Number Get end)

                //  *** End programmer edit section *** (Phone.Number Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Phone.Number Set start)

                //  *** End programmer edit section *** (Phone.Number Set start)
                this.fNumber = value;
                //  *** Start programmer edit section *** (Phone.Number Set end)

                //  *** End programmer edit section *** (Phone.Number Set end)
            }
        }
        
        /// <summary>
        /// Phone.
        /// </summary>
        //  *** Start programmer edit section *** (Phone.PhoneType CustomAttributes)

        //  *** End programmer edit section *** (Phone.PhoneType CustomAttributes)
        [NotNull()]
        public virtual IIS.TestProject20200713.PhoneType PhoneType
        {
            get
            {
                //  *** Start programmer edit section *** (Phone.PhoneType Get start)

                //  *** End programmer edit section *** (Phone.PhoneType Get start)
                IIS.TestProject20200713.PhoneType result = this.fPhoneType;
                //  *** Start programmer edit section *** (Phone.PhoneType Get end)

                //  *** End programmer edit section *** (Phone.PhoneType Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Phone.PhoneType Set start)

                //  *** End programmer edit section *** (Phone.PhoneType Set start)
                this.fPhoneType = value;
                //  *** Start programmer edit section *** (Phone.PhoneType Set end)

                //  *** End programmer edit section *** (Phone.PhoneType Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.TestProject20200713.Contact.
        /// </summary>
        //  *** Start programmer edit section *** (Phone.Contact CustomAttributes)

        //  *** End programmer edit section *** (Phone.Contact CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.TestProject20200713.Contact Contact
        {
            get
            {
                //  *** Start programmer edit section *** (Phone.Contact Get start)

                //  *** End programmer edit section *** (Phone.Contact Get start)
                IIS.TestProject20200713.Contact result = this.fContact;
                //  *** Start programmer edit section *** (Phone.Contact Get end)

                //  *** End programmer edit section *** (Phone.Contact Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Phone.Contact Set start)

                //  *** End programmer edit section *** (Phone.Contact Set start)
                this.fContact = value;
                //  *** Start programmer edit section *** (Phone.Contact Set end)

                //  *** End programmer edit section *** (Phone.Contact Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PhoneE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PhoneE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PhoneE", typeof(IIS.TestProject20200713.Phone));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Phone.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfPhone CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfPhone CustomAttributes)
    public class DetailArrayOfPhone : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.TestProject20200713.DetailArrayOfPhone members)

        //  *** End programmer edit section *** (IIS.TestProject20200713.DetailArrayOfPhone members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Phone by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Phone.
        /// </summary>
        public DetailArrayOfPhone(IIS.TestProject20200713.Contact fContact) : 
                base(typeof(Phone), ((ICSSoft.STORMNET.DataObject)(fContact)))
        {
        }
        
        public IIS.TestProject20200713.Phone this[int index]
        {
            get
            {
                return ((IIS.TestProject20200713.Phone)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.TestProject20200713.Phone dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
